### ISSUE TITLE
Implement backend for notification preferences

### ISSUE THREAD

**Issue by issa-diallo** [mynotif/mynotif-frontend#224]
## Description

Currently, the `NotificationPreferences` page allows users to select the day of the week they wish to receive notifications, as well as the number of weeks before expiration. However, integration with the backend has not yet been implemented.

## Tasks to be carried out

- [ ] Create an endpoint API to store a user's notification preferences.
- [ ] Connect the API to the `handleSubmit` function in `NotificationPreferences`.
- [ ] Handle possible errors when saving preferences.
- [ ] Ensure that data is correctly recorded and reflected in the user interface after submission.

## Code concerned

The code segment concerned is :

const handleSubmit = (e: React.FormEvent): void => {
  e.preventDefault()
  // ToDo, backend
  console.log(`Selected day: ${selectedDay}, Weeks before: ${weeksBefore}`)
}

## Additional information
- Ideally, the backend should also be able to get the user's current preferences when accessing the page, and display them as default values in the selection fields.
